openapi: 3.0.1

info:
  title: SSIDDI Data Model
  description: SSIDDI Data Model
  version: 1.0
  
servers:
  - url: http://82.223.203.200:3001/
    description: SSIDDI Test Server
    
tags:
  - name: SSIDDI Data Model
    description: SSIDDI Data Model

paths:
  /model:
    get:
      summary: Get the SSIDDI version
      responses:
        200:
          description: The SSIDDI version
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/version'
  /organisation:
    get:
      summary: Get all SSIDDI organisations  
      responses:
        200:
          description: A single organisation
          content:
            application/json:
              schema:
              type: array
              items:
                $ref: '#/components/schemas/organisation'                 
  /organisation/{id}:
    get:
      summary: Get an organisation by Id
      parameters:
      - name: id
        in: path
        description: Organisation Id
        required: true
        schema:
          type: string      
      responses:
        200:
          description: A single organisation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/organisation'                
                
components:
  schemas:
    model:
      type: object
      required:
      - version
      - organisations      
      properties:
        version:
            $ref: '#/components/schemas/version'
        organisations:
          type: array
          items:
            $ref: '#/components/schemas/organisation'
    version:
      type: string
      example: ssiddi v1
    organisation:
      type: object    
      required:
      - id
      - name
      - services
      properties:
        id:
          type: string
          example: e20993d1-2430-462b-a9d0-2f2ead3345f8
        name:
          type: string
          example: Example University
        services:
          type: array
          items:
            $ref: '#/components/schemas/service'
        sigature:
            $ref: '#/components/schemas/signature'            
    service:
      type: object    
      required:
      - id
      - name
      - accreditation
      properties:
        id:
          type: string
          example: e20993d1-2430-462b-a9d0-2f2ead3345f8
        name:
          type: string
          example: University Credential Issuance
        accreditation:
            $ref: '#/components/schemas/accreditation'       
    accreditation:
      type: object
      required:
      - accreditor
      properties:
        accreditor:
          type: string
          example: "did:sov:12345678abcdefg"
        createdAt:
          type: string
          format: date-time
          example: 2021-06-21T18:05:02Z
        expirationDate:
          type: string
          format: date-time
          example: 2022-06-21T18:05:02Z
        signature:
          $ref: '#/components/schemas/signature'
    signature:
      type: object
      properties:
        created:
          type: string
          format: date-time
          example: 2021-06-21T18:05:02Z
        text:
          type: string
          example: abc...123=
        type:
          type: string
          example: EidasSeal2021
        verificationMethod:
          type: string
          example: did:sov:234567890abcdefg
          
