openapi: 3.0.0
info:
  title: SSIDDI Data Model
  description: SSIDDI Data Model
  version: 1.0.0
  
servers:
  - url: http://82.223.203.200:3001/
    description: SSIDDI Test Server
    
tags:
  - name: SSIDDI Data Model
    description: SSIDDI Data Model

paths:
  /metadata:
    get:
      summary: Get the model version
      responses:
        '200':
          description: The model version
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/metadata'
            application/xml:
              schema:
                $ref: '#/components/schemas/metadata'                
  /organisations:
    get:
      summary: Get SSIDDI organisations by filters
      parameters:
      - in: query
        name: filter
        description: a wildcard parameter
        schema:
          type: string          
      responses:
        '200':
          description: all organisations filtered by wildcard parameter 
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/organisation' 
            application/xml:
              schema:
                type: array
                items:              
                  $ref: '#/components/schemas/organisation'                    
  /organisation/{uuid}:
    get:
      summary: Get an organisation by uuid
      parameters:
      - in: path
        name: uuid
        description: organisation uuid
        required: true
        schema:
          type: string
      - in: query
        name: lang
        description: language parameter (en as default)
        schema:
          type: string          
      responses:
        '200':
          description: a single organisation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/organisation'
            application/xml:
              schema:
                $ref: '#/components/schemas/organisation'                
  /organisation/{uuid}/services:
    get:
      summary: Get services by organisation uuid
      parameters:
      - in: path
        name: uuid
        description: Organisation uuid
        required: true
        schema:
          type: string
      - in: query
        name: lang
        description: Language parameter (en as default)
        schema:
          type: string          
      responses:
        '200':
          description: Services of a single organisation
          content:
            application/json:
              schema:
                type: array
                items:              
                  $ref: '#/components/schemas/service'
            application/xml:
              schema:
                type: array
                items:               
                  $ref: '#/components/schemas/service'                   
  /service/{uuid}:
    get:
      summary: Get a service by uuid
      parameters:
      - in: path
        name: uuid
        description: Service Id
        required: true
        schema:
          type: string
      - in: query
        name: lang
        description: Language parameter (en as default)
        schema:
          type: string          
      responses:
        '200':
          description: A single service
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/service'
            application/xml:
              schema:
                $ref: '#/components/schemas/service'                
                
components:
  schemas:
    model:
      type: object
      required:
      - metadata
      - organisations      
      properties:
        metadata:
          $ref: '#/components/schemas/metadata'
        organisations:
          type: array
          items:
            $ref: '#/components/schemas/organisation'
    metadata:      
      type: object
      properties:
        name:
          type: string
          example: ssiddi      
        version:
          type: string
          example: v1.0
      xml:
        prefix: 'ssiddi'
    organisation:
      type: object    
      required:
      - uuid
      - name
      - services
      properties:
        uuid:
          type: string
          format: uuid
          example: 12345678-abcd-1234-efgh-ab12345678cd
        name:
          type: string
          example: Example University
        services:
          type: array
          items:
            $ref: '#/components/schemas/service'      
      xml:
        prefix: 'ssiddi'   
    service:
      type: object    
      required:
      - uuid
      - description
      - accreditation
      properties:
        uuid:
          type: string
          format: uuid          
          example: 12345678-abcd-1234-efgh-ab12345678ef
        description:
          $ref: '#/components/schemas/dictionary'
        policy:
          $ref: '#/components/schemas/dictionary'
        accreditation:
          $ref: '#/components/schemas/accreditation'
        signature:
          $ref: '#/components/schemas/signature'
      xml:
        prefix: 'ssiddi'
    dictionary:
      type: object
      additionalProperties:
        type: string
      example:
        en: Hello
        es: Hola
    accreditation:
      type: object
      required:
      - accreditor
      properties:
        accreditor:
          type: string
          example: "did:sov:12345678abcdefg"
        createdAt:
          type: string
          format: date-time
          example: 2021-07-21T18:05:02Z
        expirationDate:
          type: string
          format: date-time
          example: 2022-07-21T18:05:02Z
    signature:
      type: object
      properties:
        created:
          type: string
          format: date-time
          example: 2021-06-21T18:05:02Z
        text:
          type: string
          example: abc...123=
        type:
          type: string
          example: EidasSeal2021
        verificationMethod:
          type: string
          example: did:sov:234567890abcdefg
