openapi: 3.0.1

info:
  title: SSIDDI Data Model
  description: SSIDDI Data Model
  version: 1.0.0

components:
  schemas:
    ssiddi:
      type: object
      required:
      - version
      - organisations      
      properties:
        'version':
          type: string
          example: v1
        'organisations':
          type: array
          items:
            $ref: '#/components/schemas/organisation'
    organisation:
      required:
      - id
      - name
      type: object
      properties:
        id:
          type: string
          example: e20993d1-2430-462b-a9d0-2f2ead3345f8
        name:
          type: string
          example: University
