openapi: 3.0.0
info:
  title: SSIDDI Data Model
  description: SSIDDI Data Model
  version: 1.0.0
  
servers:
  - url: http://82.223.203.200:3001/
    description: SSIDDI Test Server
    
tags:
  - name: SSIDDI Data Model
    description: SSIDDI Data Model

paths:
  /metadata:
    get:
      summary: Get the model version
      responses:
        '200':
          description: The model version
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/metadata'                 
  /organisation/{id}:
    get:
      summary: Get an organisation by Id
      parameters:
      - name: id
        in: path
        description: Organisation Id
        required: true
        schema:
          type: string
      - name: lang
        in: query
        description: Language parameter (en as default)
        schema:
          type: string          
      responses:
        '200':
          description: A single organisation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/organisation'
  /services/{id}:
    get:
      summary: Get services by organisation Id
      parameters:
      - name: id
        in: path
        description: Organisation Id
        required: true
        schema:
          type: string
      - name: lang
        in: query
        description: Language parameter (en as default)
        schema:
          type: string          
      responses:
        '200':
          description: Services of a single organisation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/service' 
  /service/{id}:
    get:
      summary: Get a service by Id
      parameters:
      - name: id
        in: path
        description: Service Id
        required: true
        schema:
          type: string
      - name: lang
        in: query
        description: Language parameter (en as default)
        schema:
          type: string          
      responses:
        '200':
          description: A single service
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/service'                   
                
components:
  schemas:
    model:
      type: object
      required:
      - metadata
      - organisations      
      properties:
        metadata:
            $ref: '#/components/schemas/metadata'
        organisations:
          type: array
          items:
            $ref: '#/components/schemas/organisation'
    metadata:
      type: string
      example: ssiddi v1
    organisation:
      type: object    
      required:
      - id
      - name
      - services
      properties:
        id:
          type: string
          example: 12345678-abcd-1234-efgh-ab12345678cd
        name:
          type: string
          example: Example University
        services:
          type: array
          items:
            $ref: '#/components/schemas/service'
        sigature:
            $ref: '#/components/schemas/signature'            
    service:
      type: object    
      required:
      - id
      - name
      - accreditation
      properties:
        id:
          type: string
          example: 12345678-abcd-1234-efgh-ab12345678cd
        name:
          type: string
          example: University Credential Issuance
        policy:
            $ref: '#/components/schemas/policy'
        accreditation:
            $ref: '#/components/schemas/accreditation'
    policy:
      type: object
      properties:
        text:
          type: string
          example: Terms and Conditions
    accreditation:
      type: object
      required:
      - accreditor
      properties:
        accreditor:
          type: string
          example: "did:sov:12345678abcdefg"
        createdAt:
          type: string
          format: date-time
          example: 2021-07-21T18:05:02Z
        expirationDate:
          type: string
          format: date-time
          example: 2022-07-21T18:05:02Z
        signature:
          $ref: '#/components/schemas/signature'
    signature:
      type: object
      properties:
        created:
          type: string
          format: date-time
          example: 2021-06-21T18:05:02Z
        text:
          type: string
          example: abc...123=
        type:
          type: string
          example: EidasSeal2021
        verificationMethod:
          type: string
          example: did:sov:234567890abcdefg
          
