openapi: 3.0.1

info:
  title: SSIDDI Data Model
  description: SSIDDI Data Model
  version: 1.0.0

components:
  schemas:
    ssiddi:
      type: object
      required:
      - version
      - organisations      
      properties:
        'version':
          type: string
          example: v1
        'organisations':
          type: array
          items:
            $ref: '#/components/schemas/organisation'
    organisation:
      required:
      - id
      - name
      - services
      type: object
      properties:
        id:
          type: string
          example: e20993d1-2430-462b-a9d0-2f2ead3345f8
        name:
          type: string
          example: "Example University"
        services:
          type: array
          items:
            $ref: '#/components/schemas/service'
    service:
      required:
      - id
      - name
      - accreditation
      type: object
      properties:
        id:
          type: string
          example: "e20993d1-2430-462b-a9d0-2f2ead3345f8"
        name:
          type: string
          example: "University Credential Issuance"
        accreditation:
            $ref: '#/components/schemas/accreditation'          
    accreditation:
      type: object
      required:
      - accreditor
      properties:
        accreditor:
          type: string
          example: "did:sov:12345678abcdefg"
        createdAt:
          type: string
          format: date-time
          example: 2021-06-21T18:05:02Z
        expirationDate:
          type: string
          format: date-time
          example: 2022-06-21T18:05:02Z
        signature:
          $ref: '#/components/schemas/signature'
    signature:
      type: object
      properties:
        created:
          type: string
          format: date-time
          example: 2021-06-21T18:05:02Z
        text:
          type: string
          example: "abc...123="
        type:
          type: string
          example: EidasSeal2021
        verificationMethod:
          type: string
          example: "did:sov:234567890abcdefg"
          
